name: 'Post TAP Files'
description: 'Greet someone and record the time'
inputs:
  github:
    description: 'The Github Context JSON object'
    required: true
    default: 'None'
  matrix:
    description: 'Matrix information on run'
    required: false
    default: 'None'
  os:
    description: 'Operating System it is being run on'
    required: true
  logtype:
    description: 'Type of Log.. e.g. (TAP, XML, ... TODO)'

runs:
  using: 'node12'
  main: 'index.js'
