name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x] #8.x, 10.x, 

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    - run: ls
    - run: pwd
    - name: Post TAP
      uses: GoogleCloudPlatform/flaky-service/packages/action@v1.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        matrix: ${{toJson(matrix)}}
        os: ${{runner.os}}
        log-type: TAP
        file-path: ${{github.workspace}}/flaky-tap-log.tap
        repo-description: ${{github.event.repository.description}}
        tag: 'Epic tag'
