name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x] #8.x, 10.x, 

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
    - name: Post TAP
      uses: ./action/action # Uses an action in the root directory
      with:
        github-actor: ${{github.actor}}
        github-repository: ${{github.repository}}
        github-repository-owner: ${{github.repository-owner}}
        github-sha: ${{github.sha}}
        github-ref: ${{github.ref}}
        github-headref: ${{github.head_ref}}
        github-baseref: ${{github.base_ref}}
        github-token: ${{github.token}}

   
